name: Build Hyperplayer

on:
  push:
    branches: [portable-version]
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Build on Linux Static (Ubuntu 24.04)
            os: ubuntu-24.04
            triplet: x64-linux
            toolchain: /usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake
            is_linux: true
          - name: Build on Linux Dynamic (Ubuntu 24.04)
            os: ubuntu-24.04
            triplet: x64-linux-dynamic
            toolchain: /usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake
            is_linux: true
          - name: Build on Linux ARM64 Static (Ubuntu 24.04)
            os: ubuntu-24.04-arm
            triplet: arm64-linux
            toolchain: /usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake
            is_linux: true
          - name: Build on Linux ARM64 Dynamic (Ubuntu 24.04)
            os: ubuntu-24.04-arm
            triplet: arm64-linux-dynamic
            toolchain: /usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake
            is_linux: true
          - name: Build on Windows (Windows Latest)
            os: windows-latest
            triplet: x64-windows
            toolchain: C:/vcpkg/scripts/buildsystems/vcpkg.cmake
            is_linux: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install dependencies on Debian-ish systems
        if: matrix.is_linux
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf autoconf-archive automake libtool libltdl-dev pkg-config ninja-build libx11-dev libxext-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxkbcommon-dev libwayland-dev libegl1-mesa-dev libasound2-dev libpulse-dev libjack-dev libxtst-dev libxss-dev libgbm-dev libdrm-dev libdbus-1-dev libibus-1.0-dev libudev-dev

      - name: Install common dependencies via vcpkg
        run: vcpkg install sdl3 sdl3-image[png] sdl3-ttf libopenmpt --triplet ${{ matrix.triplet }}

      - name: Configure cmake build
        run: |
          if [ "${{ matrix.is_linux }}" = "true" ]; then
            cmake -B build -S . -G Ninja -DCMAKE_TOOLCHAIN_FILE=${{ matrix.toolchain }} -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }} -DCMAKE_BUILD_TYPE=Release
          else
            cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{ matrix.toolchain }} -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }} -DCMAKE_BUILD_TYPE=Release
          fi
        shell: bash

      - name: Build
        run: cmake --build build --config Release

      - name: Package archive
        shell: bash
        run: |
          mkdir -p dist/hyperplayer
          if [ "${{ matrix.is_linux }}" = "true" ]; then
            # Copy executable
            cp build/hyperplayer dist/hyperplayer/
            # Copy assets
            cp build/background.png build/protracker.ttf build/PT-mousecursor.png build/hyperplayer.ini dist/hyperplayer/
          else
            # Windows
            cp build/Release/hyperplayer.exe dist/hyperplayer/
            shopt -s nullglob
            # Needed or not?
            for dll in build/Release/*.dll; do
              cp "$dll" dist/hyperplayer/
            done
            # Copy assets
            cp build/background.png build/protracker.ttf build/PT-mousecursor.png build/hyperplayer.ini dist/hyperplayer/
          fi

      - name: Make archive available for download
        uses: actions/upload-artifact@v4
        with:
          name: hyperplayer-remake-${{ matrix.triplet }}
          path: dist
          retention-days: 7
